//
//  CategoryInteractor.swift
//  Training-Adli
//
//  Created by Stella Patricia on 09/10/19.
//  Copyright (c) 2019 Adli Raihan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CategoryBusinessLogic
{
  func doSomething(request: Category.Something.Request)
}

protocol CategoryDataStore
{
  //var name: String { get set }
}

class CategoryInteractor: CategoryBusinessLogic, CategoryDataStore
{
  var presenter: CategoryPresentationLogic?
  var worker: CategoryWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Category.Something.Request)
  {
    worker = CategoryWorker()
    worker?.doSomeWork()
    
    let response = Category.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
