//
//  CategoryWorker.swift
//  Training-Adli
//
//  Created by Stella Patricia on 09/10/19.
//  Copyright (c) 2019 Adli Raihan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CategoryWorker
{
  func doSomeWork()
  {
  }
}
