//
//  ProfileModels.swift
//  Training-Adli
//
//  Created by Adli Raihan on 02/10/19.
//  Copyright (c) 2019 Adli Raihan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwiftyUserDefaults
import ObjectMapper

enum Profile
{
    // completion
    enum completion {
        case success (response : Profile.privateProfile.response)
        case failed (message : String)
    }
    // MARK: Use cases
    enum privateProfile {
        struct request {
            var accessToken : String = ConstantVariables.accessToken
            var clientId : String = ConstantVariables.clientId
            var secretKey : String = ConstantVariables.secretKey
        }
        struct response : Mappable {
            
            var id : String?
            var updatedAt : String?
            var firstName : String?
            var lastName : String?
            var twitterUsername : String?
            var portofolio : String?
            var bio : String?
            var location : String?
            var totalLikes : Int?
            var totalPhotos : Int?
            var totalCollections : Int?
            var followedByUser : Bool?
            var downloads : Int?
            var uploadRemaining : Int?
            var instagramUser : String?
            var locations : String?
            var email : String?
            var links : responseLinks?
            var username : String?
            var followers : Int?
            var imageURL : responseImage?
            
            init() {
                
            }
            
            init?(map: Map) {
                
            }
            
            mutating func mapping(map: Map) {
                id <- map["id"]
                updatedAt <- map["updated_at"]
                firstName <- map["first_name"]
                lastName <- map["last_name"]
                twitterUsername <- map["twitter_username"]
                portofolio <- map["portofolio"]
                bio <- map["bio"]
                location <- map["location"]
                totalLikes <- map["total_likes"]
                totalPhotos <- map["total_photos"]
                totalCollections <- map["total_collections"]
                followedByUser <- map["followed_by_user"]
                username <- map["username"]
                followers <- map["followers_count"]
                imageURL <- map["profile_image"]
            }
            
            struct  responseLinks {
                var _self : String?
                var _html : String?
                var _photos : String?
                var _portofolio : String?
            }
            
            struct responseImage : Mappable {
                var  _large : String?
                var  _medium : String?
                var  _small : String?
                init () {}
                init?(map: Map) {}
                mutating func mapping(map: Map) {
                    _large <- map["large"]
                    _medium <- map["medium"]
                    _small <- map["small"]
                }
                
            }
        }
        
        struct viewModel {
            var firstName : String?
            var collection : Int?
            var followers : Int?
            var username : String?
            var email : String?
            var imageURL : String?
            
            init() {} 
        }
    }
}

