//
//  ProfileWorker.swift
//  Training-Adli
//
//  Created by Adli Raihan on 02/10/19.
//  Copyright (c) 2019 Adli Raihan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ProfileWorker
{
    
    
    func getProfileUser (completion _completion : @escaping (globalEnum) -> Void ) {
        trainProvider.request(trainServices.getProfile()) { (result) in
            switch result {
            case .success(let response):
                _completion(.success(data: response))
                break
            case .failure(let error):
                "Error".createMessage(message: error.localizedDescription)
                _completion(.error(error: error.localizedDescription))
                break
            }
        }
    }
    
    func getPublicProfileUser (request : Profile.publicProfile.request , completion _completion : @escaping (globalEnum) -> Void) {
        trainProvider.request(trainServices.getPublicProfile(request: request)) { (result) in
            switch result {
            case .success(let response):
                _completion(.success(data:response))
                break
            case .failure(let error):
                _completion(.error(error: error.localizedDescription))
                break
            }
        }
    }
    
    
}

