//
//  ProfileViewController.swift
//  Training-Adli
//
//  Created by Adli Raihan on 02/10/19.
//  Copyright (c) 2019 Adli Raihan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwiftyUserDefaults
import WebKit

protocol ProfileDisplayLogic: class
{
    func displayToProfile(viewModel : Profile.privateProfile.viewModel)
    func displayToPublicProfile(response : Profile.publicProfile.response)
}

enum profileViewer {
    case _self
    case _other
    case _mod
    case _friends
    case _fromdashboard
}

class ProfileViewController: BaseViewController, ProfileDisplayLogic
{
    // Outlets
    @IBOutlet weak var openSideMenuButton: UIButton! {
        didSet {
            let image = UIImage.init(named: "ic_menu")?.withRenderingMode(.alwaysTemplate)
            openSideMenuButton.tintColor = UIColor.white
            openSideMenuButton.setImage(image, for: .normal)
            openSideMenuButton.setTitle("", for: .normal)
        }
    }
    
    @IBOutlet weak var topConstraintProfileSection: NSLayoutConstraint!
    @IBOutlet weak var profileSectionViewHolder: UIView!
    @IBOutlet weak var imageMinimalProfile: UIImageView! {
        didSet {
            imageMinimalProfile.circleRadius(withBorder: true, borderColor: .lightGray, opacity: 0.5, borderWidth: 1)
            imageMinimalProfile.clipsToBounds = true
        }
    }
    @IBOutlet weak var imageProfile: UIImageView! {
        didSet{
            imageProfile.circleRadius(withBorder: true, borderColor: .lightGray, opacity: 0.5, borderWidth: 1)
            imageProfile.clipsToBounds = true
        }
    }
    @IBOutlet weak var followButton: UIButton! {
        didSet {
            followButton.setShadow()
            followButton.circleRadius()
            followButton.backgroundColor = UIColor.init(rgb: 0x1c313a)
        }
    }
    @IBOutlet weak var messageButton: UIButton! {
        didSet {
            messageButton.backgroundColor = UIColor.white.withAlphaComponent(0)
            messageButton.setTitleColor(UIColor.init(rgb: 0x1c313a), for: .normal)
        }
    }
    
    @IBOutlet weak var leftSideMenuConstraint: NSLayoutConstraint!
    @IBOutlet weak var leftSideMenuButtonConstraintRight: NSLayoutConstraint!
    @IBOutlet weak var scrollView: UIScrollView!
    @IBOutlet weak var scrollViewContentHeights: NSLayoutConstraint!
    @IBOutlet weak var scrollViewInsideContent : UIView!
    @IBOutlet weak var tableViewProfileContent: tableViewProfileContent!
    
    @IBOutlet weak var followInContentButton: UIButton!
    @IBOutlet weak var usernameInContentLabel: UILabel!
    
    // List Of Outlet Image
    @IBOutlet weak var outletImage: UIView!
    
    
    
    //
    
    
    @IBOutlet weak var imageCollectionPrimary : UIImageView!
    @IBOutlet weak var imageCollectionSecondaryOne : UIImageView!
    @IBOutlet weak var imageCollectionSecondaryTwo : UIImageView!
    @IBOutlet weak var imageCollectionViewHolder : UIView! {
        didSet {
            imageCollectionViewHolder.constantRadius()
            imageCollectionViewHolder.setShadow()
        }
    }
    @IBOutlet weak var menuSideHideGestureView : UIView!
    @IBOutlet weak var menuSideButtonAction: UIImageView!
    @IBOutlet weak var menuSidePositionLeft: NSLayoutConstraint!
    @IBOutlet weak var menuSide: UIView!
    @IBOutlet weak var menuSideLogout: UIButton!
    
    @IBOutlet weak var usernameProfile: UILabel!
    @IBOutlet weak var followersCountProfile: UILabel!
    @IBOutlet weak var collectionsCountProfile: UILabel!
    
    @IBOutlet weak var newProfileHolder: UIView!
    
    // Costum View Object
    private var UIBackCostum : UIView?
    var finishLoading = false
    
    // List Object
    lazy var contentCell : [ UITableViewCell ] = [CollectionTableViewCell()]
    var publicProfile = Profile.publicProfile.viewModel.request.init()
    var profileViewBehavior : profileViewer = ._other
    var isCollectionZero : Bool = false
    var isMenuOpen = false
    var interactor: ProfileBusinessLogic?
    var router: (NSObjectProtocol & ProfileRoutingLogic & ProfileDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    private func setup()
    {
        let viewController = self
        let interactor = ProfileInteractor()
        let presenter = ProfilePresenter()
        let router = ProfileRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    override func viewDidLoad()
    {
        super.viewDidLoad()
        newSetupUI()
        newSetupIO()
        checkProfileBehavior()
//        setupUI()
//        setupIO()
        (self.publicProfile.username.isEmpty) ? do_getProfile() : do_getPublicProfile()
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(true)
        "DOES IT GET CALLED ? ".createMessage(message: "YES")
        checkProfileBehavior()
        attachProfileContent()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(true)
        self.tabBarController?.tabBar.isHidden = false
        if !finishLoading {
            self.setupLoading(_view: self.tableViewProfileContent)
        }
    }
    
    private func newSetupUI () {
        self.newProfileHolder.setShadow()
        self.scrollViewContentHeights.constant = self.scrollViewContentHeights.constant + 145.0
        self.scrollView.delegate = self
        self.scrollView.bounces  = false
        self.leftSideMenuConstraint.constant = -UIScreen.main.bounds.width
        self.followInContentButton.alpha = 0
    }
    
    private func newSetupIO () {
    }
    
    private func attachProfileContent () {
        self.tableViewProfileContent.initializeData(parent: self)
        self.tableViewProfileContent.isScrollEnabled = false
        self.tableViewProfileContent.bounces = false
    }
    
    private func setupUI() {
        menuSidePositionLeft.constant = -menuSide.frame.width
        menuSideHideGestureView.isHidden = true
    }
    
    private func setupIO() {
        menuSideButtonAction.isUserInteractionEnabled = true
        menuSideButtonAction.addGestureRecognizer(UITapGestureRecognizer.init(target: self, action: #selector(showSideBarMenu)))
        menuSideHideGestureView.isUserInteractionEnabled = true
        menuSideHideGestureView.addGestureRecognizer(UITapGestureRecognizer.init(target: self, action: #selector(hideSideBarMenu)))
    }
    
    private func checkProfileBehavior () {
        switch profileViewBehavior {
        case ._self:
            navigationController?.setNavigationBarHidden(true, animated: false)
            break
        case ._other:
            navigationController?.setNavigationBarHidden(true, animated: false)
            break
        case ._mod:
            navigationController?.setNavigationBarHidden(false, animated: false)
            break
        case ._friends:
            navigationController?.setNavigationBarHidden(false, animated: false)
            break
        case ._fromdashboard:
            _createBackButton()
            break
        }
    }
    
    private func _createBackButton () {
        let _hitBoxes = UIView.init(frame: .init(x: 15, y: 30, width: 50, height: 50))
        let _viewHolder = UIView.init(frame: .init(x: 0, y: 0, width: 35, height: 35))
        let _imageView = UIImageView.init(frame: .init(x: 0, y: 0, width: 35, height: 35))
        let _image = UIImage.init(named: "ic_back")?.withRenderingMode(.alwaysTemplate)
        
        _imageView.image = _image ?? UIImage()
        _imageView.tintColor = .white
        
        _viewHolder.circleRadius()
        _viewHolder.backgroundColor = UIColor.black.withAlphaComponent(0.1)
        _viewHolder.addSubview(_imageView)
        _viewHolder.setShadow()
        
        _hitBoxes.addSubview(_viewHolder)
        _hitBoxes.isUserInteractionEnabled = true
        _hitBoxes.addGestureRecognizer(UITapGestureRecognizer.init(target: self, action: #selector(_backbuttonAction)))
        
        self.UIBackCostum = _hitBoxes
        view.addSubview(UIBackCostum ?? _hitBoxes)
        openSideMenuButton.isHidden = true
        "Back Button".createMessage(message: "Created Successfully!")
    }
    
    @objc private func _backbuttonAction () {
        self.motionDismissViewController()
    }
    
    private func do_getProfile() {
        interactor?.getProfile()
    }
    
    private func do_getPublicProfile () {
        // UIAsssigned
        usernameProfile.text = publicProfile.username
        // variables
        let _publicProfile = Profile.publicProfile.request()
        _publicProfile.username = publicProfile.username
        
        // action
        interactor?.getPublicProfile(request: _publicProfile)
        
    }
    
    
    
    @objc private func showSideBarMenu () {
        menuSidePositionLeft.constant = 0
        UIView.animate(withDuration: 0.25) {
            self.view.layoutIfNeeded()
            self.menuSideHideGestureView.isHidden = false
        }
    }
    
    @objc private func hideSideBarMenu () {
        "Hide".createMessage(message: "Success")
        menuSidePositionLeft.constant = -menuSide.frame.width
        UIView.animate(withDuration: 0.25) {
            self.view.layoutIfNeeded()
            self.menuSideHideGestureView.isHidden = true
        }
    }
    
    /// Display Methods
    
    func displayToProfile(viewModel: Profile.privateProfile.viewModel) {
        if viewModel.collection == nil { isCollectionZero = true }
        else { isCollectionZero = (viewModel.collection! == 0) }
        self.collectionsCountProfile.text = "\(viewModel.collection ?? 0)"
        self.followersCountProfile.text = "\(viewModel.followers ?? 0)"
        self.usernameProfile.text = "@\(viewModel.username ?? "...." )"
        self.imageProfile.kf.setImage(with: URL.init(string: viewModel.imageURL ?? ""))
        self.finishLoading = true
        self.dismissLoading()
        self.tableViewProfileContent.reloadData()
    }
    
    func displayToPublicProfile(response: Profile.publicProfile.response) {
//        self.usernameProfile.text = response
        self.followersCountProfile.text = "\(response.followersCount)"
        self.imageProfile.kf.setImage(with: URL.init(string: response.photoProfile._medium))
        self.imageMinimalProfile.kf.setImage(with: URL.init(string: response.photoProfile._medium))
        self.isCollectionZero = true
        self.finishLoading = true
        self.dismissLoading()
        self.tableViewProfileContent.reloadData()
    }
    
    // Action button to show left side menu
    @IBAction func buttonOpenSideMenu(_ sender: Any) {
        changeButtonColor()
        self.leftSideMenuConstraint.constant = (isMenuOpen) ? -UIScreen.main.bounds.width : 0
        self.leftSideMenuButtonConstraintRight.constant = (isMenuOpen) ? 25 : UIScreen.main.bounds.width - 50
        self.isMenuOpen = !isMenuOpen
        UIView.animate(withDuration: 0.5, delay: 0, usingSpringWithDamping: 5, initialSpringVelocity: 10, options: .curveEaseInOut, animations: {
            self.view.layoutIfNeeded()
        }) {
            (finish) in
            self.scrollView.isScrollEnabled = !self.isMenuOpen
        }
    }
    
    // methods for change button tint Color
    private func changeButtonColor () {
        let imageDefault = UIImage.init(named: "ic_menu")
        let imageCloseMenu = UIImage.init(named: "ic_back")
        
        self.openSideMenuButton.tintColor = (isMenuOpen) ? UIColor.white : UIColor.black
        self.openSideMenuButton.setImage((isMenuOpen) ? imageDefault : imageCloseMenu , for: .normal)
    }
    
    // MARK: Do something
    @IBAction func buttonLogoutAction(_ sender: Any) {
        Defaults[.userAuthenticationCode] = ""
        WKWebView().clearCache()
        self.router?.routeToLogout()
    }
    
    
    override func viewDidDisappear(_ animated: Bool) {
        navigationController?.setNavigationBarHidden(true, animated: false)
    }
    
}

extension ProfileViewController  {
    
    // Button Action
    
}

extension ProfileViewController : UIScrollViewDelegate {
    
    func scrollViewDidScroll(_ scrollView: UIScrollView) {
        let yOffset = scrollView.contentOffset.y
        // I dont even know what this is
        guard yOffset > 0 else { return }
        guard scrollView == self.scrollView else { return }
        
        tableViewProfileContent.isScrollEnabled = false
        
        // Content Switcher
        if yOffset > 25 {
            self.scrollViewInsideContent.setShadow(Opacity: 0.05)
        } else {
            self.scrollViewInsideContent.setShadow(withColor: UIColor.white, Opacity: 0)
        }
        
        // Show Or Hide Username & Follo
        self.imageProfile.circleRadius()
        if yOffset == 145 {
            tableViewProfileContent.isScrollEnabled = true
            _showOrHideUsernameAndFollow()
        } else {
            _showOrHideUsernameAndFollow(hide: true)
        }
        
    }
    
    private func _showOrHideUsernameAndFollow (hide : Bool = false) {
        let alpha : CGFloat = (hide) ? 0 : 1
        self.imageProfile.circleRadius(withBorder: true, borderColor: .lightGray, opacity: 0.5, borderWidth: 1)
        UIView.animate(withDuration: 0.25) {
            self.outletImage.alpha = alpha
            self.imageProfile.alpha = 1 - alpha
            self.loadViewIfNeeded()
        }
    }
    
    
    
}
