//
//  LoginWorker.swift
//  Training-Adli
//
//  Created by Stella Patricia on 03/10/19.
//  Copyright (c) 2019 Adli Raihan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker
{
    func createAccessToken (request _request : unsplash.oauthTokenModel.tokenRequest,completion : @escaping (globalEnum) -> Void) {
        trainProvider.request(trainServices.oatuhAccessToken(request: _request)) { (result) in
            switch result {
            case .success(let response):
                "Token Access Response".createMessage(message: response.statusCode)
                completion(.success(data: response))
                break
            case .failure(let error):
                "Token Access Reponse Failed".createMessage(message: error.localizedDescription)
                completion(.error(error: error.errorDescription ?? "Error Unkown"))
                break
            }
        }
    }
}
