//
//  LoginPresenter.swift
//  Training-Adli
//
//  Created by Stella Patricia on 03/10/19.
//  Copyright (c) 2019 Adli Raihan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
    func presentCodeAuthenticationBearer(response : unsplash.oauthTokenModel.tokenResponse)
    func presentAuthenticationFailed ( message : String )
}

class LoginPresenter: LoginPresentationLogic
{
    weak var viewController: LoginDisplayLogic?
    
    // MARK: Do something
    func presentCodeAuthenticationBearer(response : unsplash.oauthTokenModel.tokenResponse) {
        var vModel = Login.authenticationCode.init()
        vModel.code = response.accessToken
        vModel.createdAt = response.createdAt
        viewController!.displayCodeAuthentication(viewModel: vModel)
    }
    
    func presentAuthenticationFailed(message: String) {
        viewController!.displayCodeAuthenticationFailed(message: message)
    }
}

