//
//  LoginViewController.swift
//  Training-Adli
//
//  Created by Stella Patricia on 03/10/19.
//  Copyright (c) 2019 Adli Raihan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import WebKit
import SwiftyUserDefaults

protocol LoginDisplayLogic: class
{
    func displayCodeAuthentication (viewModel : Login.authenticationCode)
    func displayCodeAuthenticationFailed (message : String)
}

class LoginViewController: BaseViewController, LoginDisplayLogic
{
    var interactor: LoginBusinessLogic?
    var router: (NSObjectProtocol & LoginRoutingLogic & LoginDataPassing)?
    @IBOutlet weak var addressBarLoader: UIActivityIndicatorView!
    @IBOutlet weak var webView: LoginWebView!
    @IBOutlet weak var textAddressBarWeb: UITextField!
    
    // MARK: Object lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    private func setup()
    {
        let viewController = self
        let interactor = LoginInteractor()
        let presenter = LoginPresenter()
        let router = LoginRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    override func viewDidLoad()
    {
        super.viewDidLoad()
        self.WebViewSetup()
    }
    
    // MARK: Do something
    //@IBOutlet weak var nameTextField: UITextField!
    private func WebViewSetup() {
        webView.load(URLRequest.init(url: URL.init(string: ConstantVariables.urlToGetAuthorization)!))
        webView.delegate = self
    }
    
    private func setupTextField (isOpen : Bool = true) {
        
        var _space = UIView.init()
        
        func openFunc() {
            _space = UIView.init(frame: CGRect.init(x: 0, y: 0, width: 34, height: 34))
        }
        
        func closeFunc() {
            _space = UIView.init(frame: CGRect.init(x: 0, y: 0, width: 0, height: 0))
        }
        
        ( isOpen ) ? openFunc() : closeFunc()
        textAddressBarWeb.leftViewMode = .always
        textAddressBarWeb.leftView = _space
        UIView.animate(withDuration: 0.5) {
            self.view.layoutIfNeeded()
        }
    }

    
    // when auth api success
    func displayCodeAuthentication(viewModel : Login.authenticationCode) {
        Defaults[.userAuthenticationCode] = viewModel.code ?? ""
        if Defaults[.userAuthenticationCode] != "" {
            self.router?.routeToDashboard() //
        }
    }
    // when auth api given failed
    func displayCodeAuthenticationFailed(message: String) {
        self.showAlert(_message: message)
    }
}

extension LoginViewController : loginWebViewDelegate {
    func didCommit(url: String) {
        self.textAddressBarWeb.text = url
        self.addressBarLoader.startAnimating()
        self.setupTextField()
        self.addressBarLoader.isHidden = false
    }

    func didFinish(authCode value: String) {
        self.setupTextField(isOpen: false)
        self.addressBarLoader.stopAnimating()
        self.addressBarLoader.isHidden = true
        if !value.isEmpty {
            interactor?.interactorParsingCode(CreateAuth: value)
        }
    }
}
