//
//  DashboardWorker.swift
//  Training-Adli
//
//  Created by Stella Patricia on 03/10/19.
//  Copyright (c) 2019 Adli Raihan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DashboardWorker
{
    func getAllPhotos (request _request : Dashboard.getPhotos.request, completion _completion: @escaping (globalEnum) -> Void ) {
        trainProvider.request(trainServices.getPhotos(request: _request)) { (result) in
            "Result".createMessage(message: result)
            switch result {
            case .success(let response):
                _completion(.success(data: response))
                break
            case .failure(let error):
                _completion(.error(error: error.localizedDescription))
                break
            }
        }
    }
    
    func setLikePhotos ( request _request : Dashboard.likePhotos.request, completion _completion : @escaping (globalEnum) -> Void) {
        trainProvider.request(trainServices.setActionLike(request: _request)) { (result) in
            "Result".createMessage(message: result)
            switch result {
            case .success(let response):
                _completion(.success(data: response))
                break
            case .failure(let error):
                _completion(.error(error: error.localizedDescription))
                break
            }
        }
    }
    
    func setUnlikePhotos (request _request : Dashboard.likePhotos.request, completion _completion : @escaping (globalEnum) -> Void) {
        trainProvider.request(trainServices.setActionUnlike(request: _request)) { (result) in
            "Result".createMessage(message: result)
            switch result {
            case .success(let response):
                _completion(.success(data: response))
                break
            case .failure(let error):
                _completion(.error(error: error.localizedDescription))
                break
            }
        }
    }
}

