//
//  DashboardRouter.swift
//  Training-Adli
//
//  Created by Stella Patricia on 03/10/19.
//  Copyright (c) 2019 Adli Raihan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DashboardRoutingLogic
{
    func routeToSelectedProfile()
}

protocol DashboardDataPassing
{
    var dataStore: DashboardDataStore? { get }
}

class DashboardRouter: NSObject, DashboardRoutingLogic, DashboardDataPassing
{
    weak var viewController: DashboardViewController?
    var dataStore: DashboardDataStore?
    
    // MARK: Routing
    func routeToSelectedProfile() {
        let destination = ProfileViewController.init(nibName: "ProfileViewController", bundle: nil)
        _navRoutetoSelectedProfile(source: viewController, destination: destination)
    }
    
    // MARK : Navigation
    func _navRoutetoSelectedProfile(source : DashboardViewController? , destination : ProfileViewController) {
        guard source != nil else { return }
        destination.publicProfile.username = source?.selectedUsername ?? ""
        destination.profileViewBehavior = ._fromdashboard
        source!.hidesBottomBarWhenPushed = false
        source?.show(destination, sender: nil)
    }
    
    // MARK : Data Pass (optional)
    func _dataRouteToSelectedProfile (source : DashboardDataStore , destination : inout ProfileDataStore) {
        
    }
}

